# Generated by Django 4.0.3 on 2022-04-28 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('nationality', models.CharField(max_length=64)),
                ('image', models.TextField()),
            ],
        ),
    ]
