# Generated by Django 4.0.3 on 2022-04-23 05:59

from django.db import migrations, models
import musicapi.songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('duration', musicapi.songs.models.CustomDurationField(default='')),
                ('releaseDate', models.DateField(null=True)),
                ('audioFile', models.TextField()),
            ],
        ),
    ]
