# Generated by Django 4.0.3 on 2022-04-23 20:40

from django.db import migrations, models
import musicapi.songs.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('duration', musicapi.songs.models.CustomDurationField(default='')),
                ('releaseDate', models.DateField(null=True)),
                ('audioFile', models.TextField()),
            ],
        ),
    ]
