# Generated by Django 4.0.3 on 2022-05-05 02:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('releaseDate', models.DateField()),
                ('single', models.BooleanField(default=False)),
                ('physicalStock', models.PositiveSmallIntegerField(blank=True, default=200)),
                ('physicalPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2000.0)])),
                ('digitalPrice', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2000.0)])),
                ('image', models.TextField()),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumArtists', to='artists.artist')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albumGenres', to='genres.genre')),
            ],
        ),
    ]
